################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F7xx_HAL_Driver/Src \
Drivers/WCON_SDK/Examples/AdrasteaI \
Drivers/WCON_SDK/Examples/Calypso/Calypso_Azure_PnP_Example \
Drivers/WCON_SDK/Examples/Calypso \
Drivers/WCON_SDK/Examples/CordeliaI \
Drivers/WCON_SDK/Examples/DaphnisI \
Drivers/WCON_SDK/Examples/Metis \
Drivers/WCON_SDK/Examples/MetisE \
Drivers/WCON_SDK/Examples/MultiModule_ProteusIII_TarvosIII \
Drivers/WCON_SDK/Examples/ProteusE \
Drivers/WCON_SDK/Examples/ProteusII \
Drivers/WCON_SDK/Examples/ProteusIII \
Drivers/WCON_SDK/Examples/Skoll_I \
Drivers/WCON_SDK/Examples/StephanoI \
Drivers/WCON_SDK/Examples/TarvosE \
Drivers/WCON_SDK/Examples/TarvosIII \
Drivers/WCON_SDK/Examples/TelestoIII \
Drivers/WCON_SDK/Examples/ThebeII \
Drivers/WCON_SDK/Examples/ThemistoI \
Drivers/WCON_SDK/Examples/ThyoneE \
Drivers/WCON_SDK/Examples/ThyoneI \
Drivers/WCON_SDK/Examples \
Drivers/WCON_SDK/STM32F4xx/Core/Src \
Drivers/WCON_SDK/STM32F4xx/Core/Startup \
Drivers/WCON_SDK/STM32F4xx/Drivers/STM32F4xx_HAL_Driver/Src \
Drivers/WCON_SDK/STM32F4xx/Drivers \
Drivers/WCON_SDK/STM32L0xx/Core/Src \
Drivers/WCON_SDK/STM32L0xx/Core/Startup \
Drivers/WCON_SDK/STM32L0xx/Drivers/STM32L0xx_HAL_Driver/Src \
Drivers/WCON_SDK/STM32L0xx/Drivers \
Drivers/WCON_SDK/WCON_Drivers/AdrasteaI/ATCommands \
Drivers/WCON_SDK/WCON_Drivers/AdrasteaI \
Drivers/WCON_SDK/WCON_Drivers/Calypso/ATCommands \
Drivers/WCON_SDK/WCON_Drivers/Calypso \
Drivers/WCON_SDK/WCON_Drivers/CordeliaI/ATCommands \
Drivers/WCON_SDK/WCON_Drivers/CordeliaI \
Drivers/WCON_SDK/WCON_Drivers/DaphnisI/ATCommands \
Drivers/WCON_SDK/WCON_Drivers/DaphnisI \
Drivers/WCON_SDK/WCON_Drivers/Metis \
Drivers/WCON_SDK/WCON_Drivers/MetisE \
Drivers/WCON_SDK/WCON_Drivers/ProteusE \
Drivers/WCON_SDK/WCON_Drivers/ProteusII \
Drivers/WCON_SDK/WCON_Drivers/ProteusIII \
Drivers/WCON_SDK/WCON_Drivers/Skoll_I/EZSerial_Host \
Drivers/WCON_SDK/WCON_Drivers/Skoll_I \
Drivers/WCON_SDK/WCON_Drivers/StephanoI/ATCommands \
Drivers/WCON_SDK/WCON_Drivers/StephanoI \
Drivers/WCON_SDK/WCON_Drivers/TarvosE \
Drivers/WCON_SDK/WCON_Drivers/TarvosIII \
Drivers/WCON_SDK/WCON_Drivers/TelestoIII \
Drivers/WCON_SDK/WCON_Drivers/ThebeII \
Drivers/WCON_SDK/WCON_Drivers/ThemistoI \
Drivers/WCON_SDK/WCON_Drivers/ThyoneE \
Drivers/WCON_SDK/WCON_Drivers/ThyoneI \
Drivers/WCON_SDK/WCON_Drivers/global \
Drivers/WCON_SDK/WCON_Drivers/utils \
Drivers/WCON_SDK/global \
Drivers/WCON_Drivers/AdrasteaI/ATCommands \
Drivers/WCON_Drivers/AdrasteaI \
Drivers/WCON_Drivers/Calypso/ATCommands \
Drivers/WCON_Drivers/Calypso \
Drivers/WCON_Drivers/CordeliaI/ATCommands \
Drivers/WCON_Drivers/CordeliaI \
Drivers/WCON_Drivers/DaphnisI/ATCommands \
Drivers/WCON_Drivers/DaphnisI \
Drivers/WCON_Drivers/Metis \
Drivers/WCON_Drivers/MetisE \
Drivers/WCON_Drivers/ProteusE \
Drivers/WCON_Drivers/ProteusII \
Drivers/WCON_Drivers/ProteusIII \
Drivers/WCON_Drivers/Skoll_I/EZSerial_Host \
Drivers/WCON_Drivers/Skoll_I \
Drivers/WCON_Drivers/StephanoI/ATCommands \
Drivers/WCON_Drivers/StephanoI \
Drivers/WCON_Drivers/TarvosE \
Drivers/WCON_Drivers/TarvosIII \
Drivers/WCON_Drivers/TelestoIII \
Drivers/WCON_Drivers/ThebeII \
Drivers/WCON_Drivers/ThemistoI \
Drivers/WCON_Drivers/ThyoneE \
Drivers/WCON_Drivers/ThyoneI \
Drivers/WCON_Drivers/global \
Drivers/WCON_Drivers/utils \
Drivers/global \

